// react/reacthook-mockjs/src/components/Search.jsx
import React,{useState} from 'react';

const Search = ({ search })=>{
    const [searchValue,setSearchValue] = useState("");

    const handleSearchInputChanges=e=>{
        setSearchValue(e.target.value);
    }

    const callSearchFunc=e=>{
        e.preventDefault();
        search(searchValue);
        resetInputField();
    }

    const resetInputField =()=>{
        setSearchValue("");
    }
    return(
        <form className="search">
            <input
                type="text"
                value={searchValue}
                onChange={handleSearchInputChanges}
            />
            <input onClick={callSearchFunc} type="submit" value="SEARCH"/>
        </form>
    )
}

export default Search;

// vue3/movie-search-vue/src/components/Search.vue
<template>
    <form class="search" @submit.prevent="handleSubmit">
        <input
            type="text"
            v-model="movieTitle"
        />
        <input type="submit" value="SEARCH" />
    </form>
</template>
<script setup>
import { defineProps, ref , defineEmits } from 'vue';
const props = defineProps({
    search: String
})
const emit = defineEmits(["search"])
const movieTitle = ref(props.search)
// function handleChange(event) 
// {
//     movieTitle.value = event.target.value
// }
function handleSubmit(event) {
    event.preventDefault();
    emit('search', movieTitle.value);
}
</script>
