// WeChatApp/my-app/src/bilibili/header.vue
<template>
    <div class="header-wrap">
      <div class="logo">
      </div>
      <div class="search-wrap">
        <i class="icon">
          <img src="../../assets/home/search.png" alt="">
        </i>
        <span>寻找宝贝店铺</span>
      </div>
    </div>
</template>
<script>
export default{
}
</script>

// react/react-bilibil/src/components/header/index.jsx
import React from 'react'
import { Wrapper } from './style'
import { Link } from 'react-router-dom'
import Logo from "../logo";
import Avatar from "../avatar";
export default function Header() {
  return (
    <Wrapper>
        <Link className="logo" to="/home">
            <Logo />
        </Link>
        <Link className="search-icon" to="/search">
            <i className="fa fa-search"></i>
        </Link>
        <Link className="avatar" to="/space">
            <Avatar/>
        </Link>
    </Wrapper>
  )
}
